
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Electronics for Kazza!
description: My first venture into Computer Science
theme: jekyll-theme-tactile
